name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: maksimdrachov/ubuntu-cpp

    steps:
    - uses: actions/checkout@v3
    - name: configure
      shell: bash
      run: |
        cmake --version
        mkdir build
    - name: build
      shell: bash
      run: |
        cd build
        cmake ..
        cmake --build . --target main
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
