name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maksimdrachov/ubuntu-cpp:latest
      volumes:
        - ${{github.workspace}}:/app
    steps:
    - uses: actions/checkout@v3
    - name: Building
      run: |
        cmake --version
        valgrind --version
        cd /app
        ls -a
        mkdir build
        cd build
        cmake ..
        cmake --build . --target main
        cd app
        ./main 6 3
