name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maksimdrachov/ubuntu-cpp:latest
      volumes:
        - cpp-project-template:/app
    steps:
    - name: Building
      run: |
        ls
        cmake --version
        valgrind --version
        cd /app/cpp-project-template
        mkdir build
        cd build
        cmake ..
        cmake --build . --target main
        cd app
        ./main 6 3

  static-analysis:
    runs-on: ubuntu-latest
    container: maksimdrachov/ubuntu-cpp:latest
    steps:
    - name: Clang-tidy
      run: |
        cd build
        rm CMakeCache.txt
        cmake -DENABLE_CLANG_TIDY=ON ..
        cmake --build . --target main

  valgrind-check:
    runs-on: ubuntu-latest
    container: maksimdrachov/ubuntu-cpp:latest
    steps:
    - name: Valgrind
      run: |
        cd build/app
        valgrind --leak-check=yes ./main 6 3
        valgrind --leak-check=yes ./main 6 4

  unit-tests:
    runs-on: ubuntu-latest
    container: maksimdrachov/ubuntu-cpp:latest
    steps:
    - name: Unit tests
      run: |
        cd build
        rm CMakeCache.txt
        cmake -DENABLE_TESTING=ON ..
        cmake --build . --target unit_tests
        cd tests
        ./unit_tests

  code-coverage:
    runs-on: ubuntu-latest
    container: maksimdrachov/ubuntu-cpp:latest
    steps:
    - name: Code coverage
      run: |
        cd build
        rm CMakeCache.txt
        cmake -DENABLE_TESTING=ON -DENABLE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ..
        cmake --build . --target coverage

  style:
    runs-on: ubuntu-latest
    container: maksimdrachov/ubuntu-cpp:latest
    steps:
    - name: clang-format
      run: |
        cd build
        rm CMakeCache.txt
        cmake -DENABLE_CLANG_FORMAT=ON ..
        cmake --build . --target clang-format-check

  running:
    runs-on: ubuntu-latest
    container: maksimdrachov/ubuntu-cpp:latest
    steps:
    - name: Running
      run: |
        cd build/app
        ./main 5 3
